config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/networks', to: 'networks#index'
  get '/networks/new', to: 'networks#new'
  post '/networks', to: 'networks#create'
  get '/networks/:id', to: 'networks#show'
  get '/networks/:id/edit', to: 'networks#edit'
  patch '/networks/:id', to: 'networks#update'
  delete '/networks/:id', to: 'networks#destroy'

  get '/restaurants', to: 'restaurants#index'
  get '/restaurants/new', to: 'restaurants#new'
  post '/restaurants', to: 'restaurants#create'
  get '/restaurants/:id', to: 'restaurants#show'
  get '/restaurants/:id/edit', to: 'restaurants#edit'
  patch '/restaurants/:id', to: 'restaurants#update'
  delete '/restaurants/:id', to: 'restaurants#destroy'

  get '/dishes', to: 'dishes#index'
  get '/restaurants/:id/dishes', to: 'restaurant_dishes#index', as: "restaurant_dishes"
  get '/dishes/:id', to: 'dishes#show'
  get '/restaurants/:id/dishes/new', to: 'restaurant_dishes#new', as: "restaurant_dishes_new"
  post '/restaurants/:id/dishes', to: 'restaurant_dishes#create'
  get '/dishes/:id/edit', to: 'dishes#edit'
  patch '/dishes/:id', to: 'dishes#update'
  delete '/dishes/:id', to: 'dishes#destroy'

  get '/shows', to: 'shows#index'
  get 'shows/:id', to: 'shows#show'
  get '/shows/:id/edit', to: 'shows#edit'
  patch 'shows/:id', to: 'shows#update'
  delete '/shows/:id', to: 'shows#destroy'
  
  get '/networks/:id/shows', to: 'network_shows#index'
  get 'networks/:id/shows/new', to: 'network_shows#new'
  post '/networks/:id/shows', to: 'network_shows#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates_presence_of :name, :taste
  belongs_to :restaurant

  def self.sort_by_spicy
    order(spicy: :desc)
  end

  def self.dish_count
    count
  end

  def self.is_it_spicy(dish)
    if dish.spicy == true
      p "Yes"
    else dish.spicy == false
      p "No"
    end
  end

  def self.order_alphabetically
    order(:name)
  end
end

app/models/network.rb
class Network < ApplicationRecord
  validates_presence_of :name, :established
  has_many :shows, dependent: :destroy

  def self.most_recent
    order(established: :desc)
  end

  def self.order_by_shows
    select('networks.*, COUNT(*) AS count').joins(:shows).group(:id).order(count: :asc)
  end
end

app/models/network_show.rb
class NetworkShow < ApplicationRecord
  belongs_to :network
  belongs_to :show
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :date_opened, :style
  has_many :dishes, dependent: :destroy

  def self.sort_by_date_desc
    order(date_opened: :desc)
  end

  def self.order_by_dishes
    select('restaurants.*, COUNT(*) AS count').joins(:dishes).group(:id).order(count: :desc)
  end
end

app/models/restaurant_dishes.rb
class RestaurantDishes < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :network
  validates_presence_of :name, :num_of_seasons
  validates_inclusion_of :daytime_show, in: [true, false]

  def self.shows_count
    count
  end

  def self.true_before_false
    order(daytime_show: :desc)
  end

   def self.order_by_alpha
    order(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.all
  end

  def new
  end

  def create
    dish = Dish.new({
                    name: params[:name],
                    spicy: params[:spicy],
                    taste: params[:taste]
                    })
      dish.save
      redirect_to "/dishes"
    end

    def show
      @dish = Dish.find(params[:id])
    end

    def edit
      @dish = Dish.find(params[:id])
    end

    def update
      dish = Dish.find(params[:id])
      dish.update({
                        name: params[:name],
                        spicy: params[:spicy],
                        taste: params[:taste]
                        })
        dish.save
        redirect_to "/dishes/#{dish.id}"
    end

    def destroy
      Dish.destroy(params[:id])
      redirect_to '/dishes'
    end
end

app/controllers/network_shows_controller.rb
class NetworkShowsController < ApplicationController
  def index
    @network = Network.find(params[:id])
    @shows = @network.shows.order_by_alpha if params[:sort] || 
    @shows = @network.shows.true_before_false
  end

  def new
    @network = Network.find(params[:id])
  end

  def create
    @networks = Network.find(params[:id])
    @networks.shows.create!(show_params)
    redirect_to "/networks/#{networks.id}/shows"
  end
  
  private 
  def show_params
    params.permit(:name, :daytime_show, :num_of_seasons)
  end
end 

app/controllers/networks_controller.rb
class NetworksController < ApplicationController

  def index
    @networks = Network.all.most_recent
    @networks = Network.order_by_shows if params[:sort] ||
    @networks = Network.all.most_recent
  end

  def new
  end

  def create
    network = Network.new({
                            name: params[:name],
                            established: params[:established]
                          })
    network.save
    redirect_to '/networks'
  end

  def show
    @network = Network.find(params[:id])
  end

  def edit
    @network = Network.find(params[:id])
  end

  def update
    network = Network.find(params[:id])
    network.update({
                    name: params[:name],
                    established: params[:established]
                  })
    network.save
    redirect_to "/networks/#{network.id}"
  end

  def destroy
    Network.destroy(params[:id])
    redirect_to '/networks'
  end
end

app/controllers/restaurant_dishes_controller.rb
class RestaurantDishesController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:id])
    if params[:sort]
      @dishes = @restaurant.dishes.order_alphabetically
    else
      @dishes = @restaurant.dishes
    end
  end

  # def show
  #   @restaurant = Restaurant.find(params[:id])
  # end

  def new
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.find(params[:id])
    @restaurant.dishes.create!({
                    name: params[:name],
                    spicy: params[:spicy],
                    taste: params[:taste]
                    })
      redirect_to "/restaurants/#{@restaurant.id}/dishes"
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    if params[:sort]
      @restaurants = Restaurant.order_by_dishes
    else
      @restaurants = Restaurant.all
    end
  end


  def new
  end

  def create
    restaurant = Restaurant.new({
                                name: params[:name],
                                date_opened: params[:date_opened],
                                style: params[:style]
                                })
    restaurant.save
    redirect_to '/restaurants'
    end

    def show
      @restaurant = Restaurant.find(params[:id])
    end

    def edit
      @restaurant = Restaurant.find(params[:id])
    end

    def update
      restaurant = Restaurant.find(params[:id])
      restaurant.update({
                        name: params[:name],
                        date_opened: params[:date_opened],
                        style: params[:style]
                        })
      restaurant.save
      redirect_to "/restaurants/#{restaurant.id}"
    end

    def destroy
      Restaurant.destroy(params[:id])
      redirect_to '/restaurants'
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end

  def new
    @show = Show.find(params[:id])
  end

  def create
    show = Show.new({
                    name: params[:name],
                    daytime_show: params[:daytime_show],
                    num_of_seasons: params[:num_of_seasons]
                  })
    show.save
    redirect_to '/shows'
  end

  def show
    @show = Show.find(params[:id])
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    show = Show.find(params[:id])
    show.update({
                    name: params[:name],
                    daytime_show: params[:daytime_show],
                    num_of_seasons: params[:num_of_seasons]
                  })
    show.save
    redirect_to "/shows/#{show.id}"
  end

  def destroy
    Show.destroy(params[:id])
    redirect_to '/shows'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dishes/edit.html.erb
<h1>Update Current Dish</h1>
<%= form_tag "/dishes/#{@dish.id}", method: :patch do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @dish.name %><br>
  <%= label_tag :spicy %>
  <%= text_field_tag :spicy, @dish.spicy %><br>
  <%= label_tag :taste %>
  <%= text_field_tag :taste, @dish.taste %><br>
  <%= submit_tag 'Update Dish' %>
<% end %>

app/views/dishes/index.html.erb
<h1>All Dishes</h1>

<a href="/">home</a>
<br/>

<% @dishes.sort_by_spicy.each do |dish| %>
  <h3><a href="/dishes/<%= dish.id %>"><%= dish.name %></a></h3>
  <h5><%= link_to "Update Dish", "/dishes/#{dish.id}/edit"%>
  <%= link_to 'Delete Dish', "/dishes/#{dish.id}", method: :delete %><h5/>
<% end %>

app/views/dishes/show.html.erb
<br>
<%= form_tag "/dishes" do %><br>
<h1><%= @dish.name %><h1/>
<h3>Is it spicy? <%= Dish.is_it_spicy(@dish) %><br/>
How does it taste? <%= @dish.taste %><br><br>
<%= link_to "Update Dish", "/dishes/#{@dish.id}/edit"%>
<%= link_to 'Delete Dish', "/dishes/#{@dish.id}", method: :delete %>
<% end %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationalRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Network Index', '/networks' %>
    <%= link_to 'Show Index', '/shows' %>
    <%= link_to 'Restaurant Index', '/restaurants' %>
    <%= link_to 'Dish Index', '/dishes' %>
    <%= yield %>
  </body>
</html>

app/views/network_shows/index.html.erb
<h1>List of <%= link_to "#{@network.name}", "/networks/#{@network.id}"%> Shows</h1>
<h3># of Shows: <%= @network.shows.shows_count %></h3>
<%= link_to 'Home', "/" %><br/>
<%= link_to "Create Show", "/networks/#{@network.id}/shows/new" %><br/>

<%= form_tag ("/networks/#{ @network.id }/shows"), method: :get do %>
  <%= label_tag :name, "Filter by # of Seasons:" %>
  <%= text_field_tag :num_of_seasons %>
  <%= submit_tag 'Filter' %>
<% end %>

<% @shows.each do |show| %>
  <h3><%= link_to "#{show.name}", "/shows/#{show.id}" %></h3>
  <li>Daytime Show:<%= show.daytime_show %></li>
  <li>Number of Seasons:<%= show.num_of_seasons %></li>
  <h6><%= link_to "Update #{show.name}", "shows/#{show.id}/edit" %></h6>
  <h6><%= link_to "Delete #{show.name}", "shows/#{show.id}/delete" %></h6>
<% end %>

app/views/network_shows/new.html.erb
<%= form_tag ("/networks/#{ @network.id }/shows"), method: :post do %>
  <%= label_tag :name, "Name:" %>
  <%= text_field_tag :name%><br>
  <%= label_tag :num_of_seasons, "Number of Seasons:" %>
  <%= text_field_tag :num_of_seasons%><br>
  <%= label_tag :daytime_show, "Daytime Show?" %>
  <%= hidden_field_tag :daytime_show, false %>
  <%= check_box_tag :daytime_show, true %><br>
  <%= submit_tag 'Create Show' %>
<% end %>

app/views/networks/edit.html.erb
<%= form_tag "/networks/#{@network.id}", method: :patch do %>
  <%= label_tag :name, "Name:" %>
  <%= text_field_tag :name, @network.name %><br>
  <%= label_tag :established, "Established:" %>
  <%= text_field_tag :established, @network.established %><br>
  <%= submit_tag 'Update Network' %>
<% end %>

app/views/networks/index.html.erb
<h1>All Networks</h1>

<%= link_to 'Home', "/" %><br/>
<%= link_to 'New Network', "/networks/new" %><br/>

<% @networks.most_recent.each do |network| %>
  <h3><a href="/networks/<%= network.id %>"><%= network.name %></a></h3>
  <li>Established :<%= network.established %></li>
<% end %><br>

app/views/networks/new.html.erb
<%= form_tag "/networks", method: :post do %>
  <%= label_tag :name, "Name:" %>
  <%= text_field_tag :name%><br>
  <%= label_tag :established, "Established:" %>
  <%= text_field_tag :established%><br>
  <%= submit_tag 'Create Network' %>
<% end %>

app/views/networks/show.html.erb
<h1><%= @network.name %></h1>
<li> Established: <%= @network.established %></li>
<h3><%= link_to 'List of Shows', "/networks/#{@network.id}/shows" %></h3><br/>
<%= link_to 'Create Show', "/networks/#{@network.id}/shows/new" %><br/>
<%= link_to 'Update Network', "/networks/#{@network.id}/edit" %><br/>
<%= link_to 'Delete Network', "/networks/#{@network.id}", method: :delete %><br/>
<%= link_to 'Back to Networks', "/networks" %>

app/views/restaurant_dishes/index.html.erb
<h1><%= @restaurant.name %> Menu</h1>

<%= link_to 'Sort dishes alphabetically', restaurant_dishes_path(@restaurant.id, sort: :true) %>

  <% @dishes.each do |dish| %>
    <h3><a href="/dishes/<%= dish.id %>"><%= dish.name %></a></h3>
    <p><h3>
    Is this dish spicy? <%= Dish.is_it_spicy(dish) %><br/>
    Taste profile: <%= dish.taste %><h3/></p>
    <h5><%= link_to "Update Dish", "/dishes/#{dish.id}/edit"%>
    <%= link_to 'Delete Dish', "/dishes/#{dish.id}", method: :delete %><h5/>
  <% end %>

<h3>There are <%= @restaurant.dishes.dish_count %> total dishes<h3/>
<h3><a href="/restaurants/<%= @restaurant.id %>/dishes/new">Add Dish</a></h3>

app/views/restaurant_dishes/new.html.erb
<%= form_tag ("/restaurants/#{@restaurant.id}/dishes"), method: :post do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %><br>
  <%= label_tag :spicy %>
  <%= hidden_field_tag :spicy, false %>
  <%= check_box_tag :spicy, true %><br>
  <%= label_tag :taste %>
  <%= text_field_tag :taste %><br>
  <%= submit_tag 'Create Dish' %>
<% end %>

app/views/restaurants/_ordered.html.erb
<% @restaurants.sort_date_desc.each do |restaurant| %>
  <h3><a href="/restaurants/<%= restaurant.id %>"><%= restaurant.name %> <% restaurant.dish_count %></a></h3>
  <h3><%= restaurant.date_opened %><h3/>
<% end %>

app/views/restaurants/edit.html.erb
<%= form_tag "/restaurants/#{@restaurant.id}", method: :patch do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @restaurant.name %><br>
  <%= label_tag :date_opened %>
  <%= text_field_tag :date_opened, @restaurant.date_opened %><br>
  <%= label_tag :style %>
  <%= text_field_tag :style, @restaurant.style %><br>
  <%= submit_tag 'Update Restaurant' %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<a href="/">home</a>
<br/>
<%= link_to 'Sort by number of dishes', restaurants_path(sort: :count) %>

<% @restaurants.sort_by_date_desc.each do |restaurant| %>
  <% if current_page?("/restaurants/#{params[:sort]}") %>
    <h3><a href="/restaurants/<%= restaurant.id %>"><%= restaurant.name %></a></h3>
    <% else %>
    <h3><a href="/restaurants/<%= restaurant.id %>"><%= restaurant.name %></a> contains <%= restaurant.dishes.dish_count %> dishes</h3>
    <% end %>
  <h3>Opened on <%= restaurant.date_opened %><h3/>
  <h5><%= link_to "Edit Restaurant", "/restaurants/#{restaurant.id}/edit" %>
  <%= link_to "Delete Restaurant", "/restaurants/#{restaurant.id}", method: :delete %><h5/>
<% end %>

<a href="/restaurants/new">New Restaurant</a>

app/views/restaurants/new.html.erb
<p>Enter a new restaurant</p>
<%= form_tag "/restaurants", method: :post do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :date_opened %><br>
  <%= text_field_tag :date_opened %><br>
  <%= label_tag :style %><br>
  <%= text_field_tag :style %><br>
  <%= submit_tag 'Create Restaurant' %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Opened on <%= @restaurant.date_opened %><br/>
Style: <%= @restaurant.style %></p>
<a href="/restaurants/<%= @restaurant.id %>/dishes">Featured Dishes</a><br/>

<a href="/restaurants/<%= @restaurant.id %>/edit">Update Restaurant</a>
  <br/>
<%= link_to 'Delete Restaurant', "/restaurants/#{@restaurant.id}", method: :delete %>

app/views/shows/edit.html.erb
<%= form_tag "/shows/#{@show.id}", method: :patch do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @show.name %><br>
  <%= label_tag :num_of_seasons, "Number of Seasons:" %>
  <%= text_field_tag :num_of_seasons, @show.num_of_seasons %><br>
  <%= label_tag :daytime_show, "Daytime Show?" %>
  <%= hidden_field_tag :daytime_show, false %>
  <%= check_box_tag :daytime_show, true %><br>
  <%= submit_tag 'Submit Update' %>
<% end %>

app/views/shows/index.html.erb
<h1>All Shows</h1>
<%= link_to 'Home', root_path %>

<% @shows.true_before_false.each do |show| %>
  <h3><%= link_to "#{show.name}", "/shows/#{show.id}" %></h3>
  <li>Daytime Show:<%= show.daytime_show %></li>
  <li>Number of Seasons:<%= show.num_of_seasons %></li>
  <h6><%= link_to "Update #{show.name}", "shows/#{show.id}/edit" %></h6>
  <h6><%= link_to "Delete #{show.name}", "shows/#{show.id}/delete" %></h6>
<% end %>

app/views/shows/show.html.erb
<h1><%= @show.name %></h1>
<li> Daytime Show: <%= @show.daytime_show %></li>
<li> Number of Seasons: <%= @show.num_of_seasons %></li><br>
<%= link_to 'Update Show', "/shows/#{@show.id}/edit" %><br>
<%= link_to 'Delete Show', "/shows/#{@show.id}/delete", method: :delete %><br/>
<%= link_to 'Back to Shows', "/shows" %>

app/views/welcome/index.html.erb
<h2>Welcome to Relational Rails</h2>
<ul>
  <li><a href="/networks">Network Index</a></li>
  <li><a href="/restaurants">Restaurant Index</a></li>
</ul>